[AIRFLOW-3844] Move to batch_alter_table to support Sqlite
Otherwise we'll end up with:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/airflow/airflow/bin/airflow", line 32, in <module>
    args.func(args)
  File "/airflow/airflow/bin/cli.py", line 1139, in resetdb
    db.resetdb()
  File "/airflow/airflow/utils/db.py", line 332, in resetdb
    initdb()
  File "/airflow/airflow/utils/db.py", line 89, in initdb
    upgradedb()
  File "/airflow/airflow/utils/db.py", line 310, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/airflow/airflow/migrations/env.py", line 93, in <module>
    run_migrations_online()
  File "/airflow/airflow/migrations/env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/airflow/airflow/migrations/versions/cd60eda52543_add_dag_model_foreign_keys.py", line 38, in upgrade
    None, "dag_run", "dag", ["dag_id"], ["dag_id"], ondelete="CASCADE"
  File "<string>", line 8, in create_foreign_key
  File "<string>", line 3, in create_foreign_key
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/ops.py", line 570, in create_foreign_key
    return operations.invoke(op)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 135, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "/usr/local/lib/python3.6/site-packages/alembic/ddl/sqlite.py", line 34, in add_constraint
    "No support for ALTER of constraints in SQLite dialect")
NotImplementedError: No support for ALTER of constraints in SQLite dialect